In [29]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [3]:
data=pd.read_csv('/content/canada_per_capita_income.csv')
canada_df=pd.DataFrame(data)
canada_df.head()

year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [7]:
reg=linear_model.LinearRegression()
reg.fit(canada_df[['year']],canada_df['per capita income (US$)'])
reg.predict([[2020]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([41288.69409442])

In [6]:
data=pd.read_csv('/content/salary.csv')
salary_df=pd.DataFrame(data)
salary_df.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [16]:
salary_df.dropna(inplace=True)
salary_df

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [14]:
reg1=linear_model.LinearRegression()
reg1.fit(salary_df[['YearsExperience']],salary_df['Salary'])
reg1.predict([[12]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([139049.67495398])

In [15]:
data=pd.read_csv('/content/hiring.csv')
hiring_df=pd.DataFrame(data)
hiring_df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [18]:
hiring_df.dropna(inplace=True)

In [21]:
hiring_df['experience'].unique()

array(['five', 'two', 'seven', 'three', 'eleven'], dtype=object)

In [22]:
hiring_df.replace('five',5,inplace=True)
hiring_df.replace('two',2,inplace=True)
hiring_df.replace('seven',7,inplace=True)
hiring_df.replace('three',3,inplace=True)
hiring_df.replace('eleven',11,inplace=True)

<ipython-input-22-ca724908f43d>:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  hiring_df.replace('eleven',11,inplace=True)


In [23]:
hiring_df['experience'].unique()

array([ 5,  2,  7,  3, 11])

In [24]:
model=linear_model.LinearRegression()
model.fit(hiring_df[['test_score(out of 10)','interview_score(out of 10)','experience']],hiring_df['salary($)'])
model.predict([[2,9,6]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([58192.45072518])

In [25]:
model.predict([[12,10,10]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([90757.15879509])

In [33]:
companies_df=pd.DataFrame(pd.read_csv('/content/1000_Companies.csv'))

In [34]:
companies_df.dropna(inplace=True)

In [35]:
companies_df['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [36]:
companies_df.replace('New York',1,inplace=True)
companies_df.replace('California',2,inplace=True)
companies_df.replace('Florida',3,inplace=True)


<ipython-input-36-be21ae47207d>:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  companies_df.replace('Florida',3,inplace=True)


In [37]:
model1=linear_model.LinearRegression()
model1.fit(companies_df[['R&D Spend','Administration','Marketing Spend','State']],companies_df['Profit'])
model1.predict([[91694.48, 515841.3, 11931.24,3]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([510745.17756471])